### ISSUE TITLE
 failed to extract shortcode: template for shortcode "speakerdeck" not found

### ISSUE THREAD

**Issue by Tetizera-zz** [rayjolt/hugo-multilingual-example#2]
I ran `hugo server` and `hugo server -D`and got this issue in both of them. I guess the issue is self-explanatory, but a template for a shortcode is missing.

**Comment by rayjolt** [comment]
Thanks for the report. It looks like the `speakerdeck` shortcode was [removed way back in Hugo 0.42](https://github.com/gohugoio/hugo/issues/4830), so I guess this repo has been broken since then. When I tried to run the server just now I got several other errors and warnings as well, so I will clean them all up and update the repo later on.

**Comment by rayjolt** [comment]
@Tetizera This has now been fixed in the master and bilingual branches, along with the other errors that were appearing. Please try again with the latest commit and see if it works for you.
